name: "OIDC Authentication"
guid: "EF25B893-BA73-4444-928C-01CD0E695AD4"
imageUrl: "https://raw.githubusercontent.com/eddymoulton/jellyfin-plugin-oidc/main/img/logo.png"
version: "0.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "eddymoulton"
overview: "Authenticate users against an OIDC provider."
description: |
  This plugin allows users to sign in through an OIDC provider (such as Google, Facebook, or your own provider). This enables one-click signin.
  Review documentation at https://github.com/eddymoulton/jellyfin-plugin-oidc
category: "Authentication"
artifacts:
  - "SSO-Auth.dll"
  - "Duende.IdentityModel.OidcClient.dll"
  - "Duende.IdentityModel.dll"
changelog: |
  0.0.0.0 - Forked
