name: "Autolabel PRs"

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/autolabel.yaml@91aa56610cd3321f8897bbe2657c1743b3df3436 # master
    with:
      repository-name: eddymoulton/jellyfin-plugin-oidc
    secrets:
      token: ${{ secrets.RELEASE_PAT }}
