name: "Build"

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@c66b7d88b5febaa6dd685c13b60e5e2c1d3d01db # master
