name: "Release Drafter & Prep PR"

on:
  push:
    branches: [main]
    paths-ignore: [build.yaml]
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@master
    with:
      repository-name: eddymoulton/jellyfin-plugin-oidc
    secrets:
      token: ${{ secrets.RELEASE_PAT }}
